apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot-test
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot-test
    spec:
      containers:
      - image: phanikumary1995/test-app
        imagePullPolicy: Always
        name: springboot-test
        ports:
        - name: springboot-test
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot-test
  name: springboot-test
spec:
#  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot-test
  clusterIP: None
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-test
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-test
  name: mongo-test
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-test
